# This workflow will do a clean install of node dependencies, build the source code and attach it to the release
name: Build

on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.1]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bump npm version and build
      - run: |
              echo ${{ github.event.release.tag_name }}
              npm version ${{ github.event.release.tag_name }}
              ls
              npm i pkg
              npm i
              npm run build-win-x64
              npm run build-mac-x64
              npm run build-win-x86
      - name: Upload release binaries
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
